language: php

sudo: required

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

services:
  - mysql

before_install:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'CREATE DATABASE test;'

install: composer install