language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
 - MYSQL_VERSION=5.6
 - MYSQL_VERSION=5.7
 - MYSQL_VERSION=8.0
 - DB_HOST=172.17.0.2

sudo: required

services:
  - docker

before_install:
  - bash ./start_db.sh
  - docker ps -a

install: composer install

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - vendor/bin/test-reporter

