language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - MYSQL_VERSION=5.6

dist: trusty

sudo: required

services:
  - docker

before_install:
  - "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - sudo /etc/init.d/mysql stop
  - make start_db V=$MYSQL_VERSION

install: composer install

before_script:
  - mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - vendor/bin/test-reporter


